### ISSUE TITLE
Unix socket support

### ISSUE THREAD

**Issue by cyberb** [mautrix/python#164]
Dendrite and whatsapp bridge (go lib) already support unix socket connection using the following config:
```
homeserver:
  address: unix:///var/snap/matrix/current/matrix.socket
appservice:
  address: unix:///var/snap/matrix/current/whatsapp.socket
  hostname: /var/snap/matrix/current/whatsapp.socket
```
Is it possible with python lib (for example telegram)?
If not I will try to add the support.
